name: Bump Comfig Web

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Change reason"
        required: true
        type: string
        default: "bump comfig web"
  schedule:
    - cron: "0 12 * * *"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: main
      - name: Commit bump
        run: |
          git config user.email "support@mastercomfig.com"
          git config user.name "mastercoms"
          git commit --allow-empty -m "web data update: ${{ github.event.inputs.reason || 'daily update' }}"
          git push
